### ISSUE TITLE
improvement ideas

### ISSUE THREAD

**Issue by stevenvachon** [sorribas/each-series#1]
- sync version
- return a native `Promise` ~~instead of using another function~~ in addition to the callback
- swap `iterator`'s `argument` indexes 1 and 2 (`i` and `done`)
- rename `done` to `next` in documentation

``` js
var each = require("each-series");

each([1,2,3,4,5,6,7], function(el, next, i) {
    setTimeout(function() {
        console.log(el);
        next();
    }, 100 - (el * 10));
}).then(function() {
    console.log('Done!');
}).catch(function(err) {
    //throw err;
});


each.sync(...);
```

I can write a PR if you'll accept it.

**Comment by sorribas** [comment]
Hey there. I prefer the callback version. I feel  like if this is to be done with promises it should be a different module. Feel free to rename `done` to `next` in the docs.

I also don't get the purpose of the sync version. How is it different to `array.forEach` ?

**Comment by stevenvachon** [comment]
How about support for both a callback and for promises?

A sync version would simply not use `process.nextTick` and differs from `.forEach` in that it requires the use of `next()`.

**Comment by sorribas** [comment]
I'm happy with the interface as it is. As for promises, as I said, I think it should be done by a different module. :).

**Comment by stevenvachon** [comment]
In case anyone comes searching for the same thing, I found this: [promise-each](https://npmjs.com/promise-each).
